---
title: Jardinateur.Github.Io
timezone: UTC
collections:
  movies:
    title: Movies
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Le Jardinateur
description: Le simple blog de l'univers du Jardinateur
author: Kevie Krutz
theme: jekyll-theme-minimal
